// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWCl1SRt0mkdxhJCl12cRqBTN_o5org_8',
    appId: '1:264950537242:web:1a10f30244165199b205a3',
    messagingSenderId: '264950537242',
    projectId: 'petcareapp-95b81',
    authDomain: 'petcareapp-95b81.firebaseapp.com',
    databaseURL: 'https://petcareapp-95b81-default-rtdb.firebaseio.com',
    storageBucket: 'petcareapp-95b81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk_j5DDe0hYHDm0ROM-zw3Vn5Fj62h7ek',
    appId: '1:264950537242:android:819753304e26f9b3b205a3',
    messagingSenderId: '264950537242',
    projectId: 'petcareapp-95b81',
    databaseURL: 'https://petcareapp-95b81-default-rtdb.firebaseio.com',
    storageBucket: 'petcareapp-95b81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXl19Tr8kTeGU-D7i9ChKnrzfLjv5mKTw',
    appId: '1:264950537242:ios:3d28dca104002609b205a3',
    messagingSenderId: '264950537242',
    projectId: 'petcareapp-95b81',
    databaseURL: 'https://petcareapp-95b81-default-rtdb.firebaseio.com',
    storageBucket: 'petcareapp-95b81.appspot.com',
    iosBundleId: 'com.example.petCareApp',
  );

}